### ISSUE TITLE
Pytest fails on Actions but not Locally using Pyjulia

### ISSUE THREAD

**Issue by guilyx** [JuliaPy/pyjulia#432]
Hey everyone,

I'm using Pyjulia to call functions from a Julia project and it works fine (thanks for the tool!) locally. I set up a Github Actions for my project and the tests failed at the `_ = julia.Julia(compiled_modules=False)` line every time.

Here's the log:

```
tests/test_pddl.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/pddl.py:10: in <module>
    _ = julia.Julia(compiled_modules=False)
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/julia/core.py:680: in __init__
    self.__julia = Julia(*args, **kwargs)
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/julia/core.py:503: in __init__
    self._call(IMPORT_PYCALL)
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/julia/core.py:538: in _call
    self.check_exception(src)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <julia.core.Julia object at 0x7f9935ede910>
src = 'const PyCall = Base.require(Base.PkgId(Base.UUID("438e738f-606a-5dbb-bf0a-cddfbfd45ab0"), "PyCall"))'

    def check_exception(self, src="<unknown code>"):
        exoc = self.api.jl_exception_occurred()
        logger.debug("exception occured? %s", str(exoc))
        if not exoc:
            # logger.debug("No Exception")
            self.api.jl_exception_clear()
            return
    
        # If, theoretically, an exception happens in early stage of
        # self.__init__, showerror and sprint as below does not work.
        # Let's use jl_typeof_str in such case.
        try:
            sprint = self.sprint
            showerror = self.showerror
        except AttributeError:
            res = None
        else:
            res = self.api.jl_call2(self._convert, self._PyObject, exoc)
        if res is None:
            exception = self.api.jl_typeof_str(exoc).decode('utf-8')
        else:
            exception = sprint(showerror, self._as_pyobj(res))
        raise JuliaError(u'Exception \'{}\' occurred while calling julia code:\n{}'
>                        .format(exception, src))
E       julia.core.JuliaError: Exception 'ArgumentError' occurred while calling julia code:
E       const PyCall = Base.require(Base.PkgId(Base.UUID("438e738f-606a-5dbb-bf0a-cddfbfd45ab0"), "PyCall"))

/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/julia/core.py:588: JuliaError
```

Here's my action: 

```yml
name: PlarserApp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.5
    - uses: actions/checkout@v1.0.0
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.4.1'
    - name: Install PDDL.jl
      run: |
        julia --color=yes -e 'using Pkg; Pkg.add(Pkg.PackageSpec(path="https://github.com/APLA-Toolbox/PDDL.jl"))'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install julia
    - name: Lint with flake8
      run: |
        python -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
```

Not sure what could cause this: maybe there's something I didn't install ? Maybe it's the versions I'm using ?

Thanks anyways!
